/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SigninIndexImport } from './routes/signin/index'
import { Route as ProfileProfileIdIndexImport } from './routes/profile/$profileId/index'
import { Route as ProfileProfileIdStoriesImport } from './routes/profile/$profileId.stories'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SigninIndexRoute = SigninIndexImport.update({
  id: '/signin/',
  path: '/signin/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileProfileIdIndexRoute = ProfileProfileIdIndexImport.update({
  id: '/profile/$profileId/',
  path: '/profile/$profileId/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileProfileIdStoriesRoute = ProfileProfileIdStoriesImport.update({
  id: '/profile/$profileId/stories',
  path: '/profile/$profileId/stories',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/signin/': {
      id: '/signin/'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninIndexImport
      parentRoute: typeof rootRoute
    }
    '/profile/$profileId/stories': {
      id: '/profile/$profileId/stories'
      path: '/profile/$profileId/stories'
      fullPath: '/profile/$profileId/stories'
      preLoaderRoute: typeof ProfileProfileIdStoriesImport
      parentRoute: typeof rootRoute
    }
    '/profile/$profileId/': {
      id: '/profile/$profileId/'
      path: '/profile/$profileId'
      fullPath: '/profile/$profileId'
      preLoaderRoute: typeof ProfileProfileIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninIndexRoute
  '/profile/$profileId/stories': typeof ProfileProfileIdStoriesRoute
  '/profile/$profileId': typeof ProfileProfileIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninIndexRoute
  '/profile/$profileId/stories': typeof ProfileProfileIdStoriesRoute
  '/profile/$profileId': typeof ProfileProfileIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/signin/': typeof SigninIndexRoute
  '/profile/$profileId/stories': typeof ProfileProfileIdStoriesRoute
  '/profile/$profileId/': typeof ProfileProfileIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/profile/$profileId/stories'
    | '/profile/$profileId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/signin' | '/profile/$profileId/stories' | '/profile/$profileId'
  id:
    | '__root__'
    | '/'
    | '/signin/'
    | '/profile/$profileId/stories'
    | '/profile/$profileId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SigninIndexRoute: typeof SigninIndexRoute
  ProfileProfileIdStoriesRoute: typeof ProfileProfileIdStoriesRoute
  ProfileProfileIdIndexRoute: typeof ProfileProfileIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SigninIndexRoute: SigninIndexRoute,
  ProfileProfileIdStoriesRoute: ProfileProfileIdStoriesRoute,
  ProfileProfileIdIndexRoute: ProfileProfileIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/signin/",
        "/profile/$profileId/stories",
        "/profile/$profileId/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/signin/": {
      "filePath": "signin/index.tsx"
    },
    "/profile/$profileId/stories": {
      "filePath": "profile/$profileId.stories.tsx"
    },
    "/profile/$profileId/": {
      "filePath": "profile/$profileId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
