spring:
  http:
    client:
      connect-timeout: 30s
      read-timeout: 120s
  application:
    name: owl
  ai:
    openai:
      chat:
        options:
          model: gpt-4o
      # Line for the images
      api-key: ${openai.api.key}
  datasource:
    url: ${DB_BASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  config:
    import: optional:file:.env[.properties]
gpt:
  prompt-template: |
    I will provide you words, and I would like you to create
    a short tale out of those words in Language: %s. 
    If Language is en generate story it in english, 
    if Language is sv generate story in Swedish.
    Story should be between 50 and 70 words, 
    and it should be something clever and nice, suitable for small kids to read. 
    Give it a fitting title as well. Use a single line break to separate the title 
    from the tale. The words are related to hero, the place, the friend, what they were doing, how they feel: %s, %s, %s, %s, %s.

  api-url: ${openai.api.url}
  model: ${openai.model}

