name: Build and deploy frontend to GCP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_URL: europe-north1-docker.pkg.dev/regal-marking-409018/cloud-run-source-deploy/owl-night-reads/owl-night-reads:${{ github.sha }}
    #the last part is service name
    steps:
      - uses: actions/checkout@v3

      - id: "auth"
        name: Authenticate GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Use gcloud CLI
        run: gcloud info

      - name: Configure docker
        run: gcloud auth configure-docker europe-north1-docker.pkg.dev

      - name: Docker Build
        run: docker build --no-cache -t ${{ env.IMAGE_URL }} ./frontend -f ./frontend/Dockerfile \
            --build-arg CLERK_API_KEY=${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }}

      - name: Docker Push
        run: docker push $IMAGE_URL

      - name: Update Cloud Run service
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          region: europe-north1
          service: owl-night-reads
          image: ${{ env.IMAGE_URL }}